---
sidebar: sidebar 
permalink: workflows/wf_create_snapshot.html 
keywords:  
summary:  
---
= Cree una instantánea para una aplicación gestionada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede crear una instantánea para una aplicación gestionada específica.



=== Antes de empezar

Debe tener el ID de la aplicación gestionada para la que desea crear una instantánea. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones gestionadas"] para localizar la aplicación.



=== 1. Crear una snapshot

Realice la siguiente llamada de API de REST.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /Accounts/{account_id}/k8s/v1/managedApps/{managedApp_id}/apps 
|===


===== Parámetros de entrada adicionales

Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación gestionada | Ruta | Sí | Identifica la aplicación administrada donde se creará la instantánea. 


| JSON | Cuerpo | Sí | Proporciona los parámetros para la instantánea. Vea el ejemplo siguiente. 
|===


===== Ejemplo de entrada JSON

[source, json]
----
{
  "type": "application/astra-appSnap",
  "version": "1.0",
  "name": "snapshot-david-1"
}
----


===== Ejemplo de curl: Cree una instantánea para la aplicación

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps' --header 'Content-Type: application/astra-appSnap+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
----