---
sidebar: sidebar 
permalink: workflows/wf_list_snapshots.html 
keywords:  
summary:  
---
= Enumere las instantáneas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede enumerar las instantáneas que se han realizado para una aplicación administrada específica.



=== Antes de empezar

Debe tener el ID de la aplicación gestionada para la que desea mostrar las instantáneas. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones gestionadas"] para localizar la aplicación.



=== 1. Enumere las instantáneas

Realice la siguiente llamada de API de REST.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| OBTENGA | /Accounts/{account_id}/k8s/v1/managedApps/{managedApp_id}/apps 
|===


===== Parámetros de entrada adicionales

Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="15,10,10,65"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación gestionada | Ruta | Sí | Identifica la aplicación administrada a la que pertenecen las instantáneas enumeradas. 


| cuente | Consulta | No | Si `count=true` el número de instantáneas se incluye en la sección de metadatos de la respuesta. 
|===


===== Ejemplo de curl: Devuelve todas las instantáneas de la aplicación

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Ejemplo curl: Devuelve todas las instantáneas de la aplicación y el recuento

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps?count=true' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Ejemplo de resultado JSON

[source, json]
----
{
  "items": [
    {
      "id": "dc2974ae-f71d-4c81-91b5-f96cf72dc3ba",
      "metadata": {
        "createdBy": "fb093413-b6fc-4a64-a48a-afc32ada8537",
        "creationTimestamp": "2021-06-04T21:23:14Z",
        "modificationTimestamp": "2021-06-04T21:23:14Z",
        "labels": []
      },
      "snapshotAppAsset": "4547658d-cc06-4c1d-ad8a-4a05274d0db0",
      "snapshotCreationTimestamp": "2021-06-04T21:23:47Z",
      "name": "test-postgres-app-snapshot-20210604212213",
      "state": "completed",
      "stateUnready": [],
      "type": "application/astra-appSnap",
      "version": "1.0"
    }
  ],
  "metadata": {
    "count": 1
  }
}
----