---
sidebar: sidebar 
permalink: workflows/wf_restore_app_backup.html 
keywords:  
summary:  
---
= Restaurar una aplicación gestionada desde una copia de seguridad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede restaurar una aplicación administrada creando una nueva aplicación a partir de una copia de seguridad.



=== 1. Seleccione la aplicación administrada que desea restaurar

Realice el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones gestionadas"] y seleccione la aplicación que desea clonar. Se necesitan varios valores de recursos para la llamada DE REST utilizada para clonar la aplicación.



=== 2. Seleccione la copia de seguridad que desea utilizar

Realice el flujo de trabajo link:wf_list_backups.html["Enumere los backups"] y seleccione la copia de seguridad que desea usar.



=== 3. Restaure la aplicación

Realice la siguiente llamada de API de REST. Debe proporcionar el ID para un backup (como se muestra a continuación) o una copia Snapshot.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUESTO | /Account/{accountID}/k8s/v1/managedApps/{AppID} 
|===


===== Parámetros de entrada adicionales

Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| JSON | Cuerpo | Sí | Proporciona los parámetros para la aplicación clonada. Vea el ejemplo siguiente. 
|===


===== Ejemplo de entrada JSON

[source, json]
----
{
  "type": "application/astra-managedApp",
  "version": "1.2",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----


===== Ejemplo de curl: Restaure una aplicación in situ a partir de un backup

[source, curl]
----
curl --location -i --request PUT 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<APP_ID>' --header 'Content-Type: application/astra-managedApp+json' --header '*/*' --header 'ForceUpdate: true' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
----